// Auto-generated. ~500 short quotes for the AFK lock screen.
window.SERENE_QUOTES = [
"Breathe. This moment is enough.",
"You are allowed to rest.",
"The quiet is not empty. It is full of answers.",
"Slow is smooth. Smooth is fast.",
"Peace is a practice, not a place.",
"Return to your breath.",
"You do not have to be productive to be worthy.",
"Stillness is a form of strength.",
"Let the day arrive on its own terms.",
"Softness is not weakness.",
"You are the sky. Everything else is just weather.",
"Presence over performance.",
"A calm mind is a superpower.",
"Sit with what is. It will pass.",
"The pause is where clarity lives.",
"Silence is a language too.",
"Rest is not a reward. It is a requirement.",
"You can begin again, any moment.",
"Nothing needs fixing right now.",
"Let it be simple.",
"Move at the speed of trust.",
"Small breaths, small steps, forward motion.",
"You are safe in this moment.",
"There is nowhere else you need to be.",
"Notice one beautiful thing today.",
"Let go of the shape you thought today would take.",
"The mind is a garden. Tend it gently.",
"Ease is a valid pace.",
"You do not owe anyone your urgency.",
"Slow the day down. Speed will find you.",
"Be soft with yourself. You are doing your best.",
"Talk to yourself like someone you love.",
"You are not behind. You are becoming.",
"Rest is productive.",
"Healing is not linear. Neither is progress.",
"You are allowed to change your mind.",
"You do not need to earn your worth.",
"The way you speak to yourself matters.",
"Your feelings are information, not instructions.",
"Being human is enough.",
"You are more than your worst day.",
"Give yourself the grace you give others.",
"You are allowed to take up space.",
"Your value is not your output.",
"Being tired is not a character flaw.",
"You are enough, exactly as you are today.",
"Feelings are visitors. Let them come and go.",
"You are permitted to disappoint people to protect your peace.",
"The bravest thing today may be to rest.",
"Softness is a form of self-respect.",
"You do not have to justify how you feel.",
"You are worthy of your own kindness.",
"Show up as you are.",
"It is okay to feel two things at once.",
"You are not a burden. You are a person.",
"Being gentle with yourself is not giving up.",
"Take the pressure off. You will figure it out.",
"Growth needs rest to happen.",
"There is no rush to become anything.",
"You are allowed to start again, and again, and again.",
"A little every day beats a lot once in a while.",
"Progress is quiet. Trust it.",
"The next right thing is enough.",
"Small habits, compounded, become identity.",
"You do not have to see the whole staircase to take the first step.",
"Consistency is more important than intensity.",
"The magic is in the boring days.",
"Discipline is a form of self-love.",
"Show up. That is the whole trick.",
"Direction matters more than speed.",
"You cannot skip the middle. It is where the work happens.",
"Motivation is a mood. Systems are a habit.",
"You are allowed to outgrow old versions of yourself.",
"The path becomes clear as you walk it.",
"Every day is a new draft.",
"You will look back on today with tenderness.",
"Start before you feel ready.",
"Momentum begins with one small motion.",
"The habit is the goal.",
"Repetition is not boring. It is becoming.",
"Do it badly. Do it anyway.",
"Growth loves the unglamorous.",
"You are one honest attempt away from momentum.",
"Trust the practice, not the mood.",
"Do it tired.",
"Your future self is watching. Make them proud, quietly.",
"Standards protect the version of you that you want to become.",
"Effort compounds. So does neglect.",
"The work is the reward.",
"Better a little today than perfect never.",
"Name it to tame it.",
"You are not your thoughts. You are the one noticing them.",
"Anxiety lies. Curiosity tells the truth.",
"When in doubt, breathe out longer than in.",
"A confused mind says no. A quiet mind gets clear.",
"Write it down. The page will hold it for you.",
"Overthinking is a shield you can put down.",
"You do not have to solve everything before you sleep.",
"Give your mind a task, or give it a rest.",
"Certainty is rare. Direction is enough.",
"Not every thought deserves your attention.",
"Do the next honest thing.",
"Doubt is a signal to slow down, not to stop.",
"Feelings pass through you. Do not build a house for them.",
"You cannot think your way out of a body problem. Move.",
"Sunlight is a nervous system reset.",
"Water first, decisions later.",
"Sleep is a strategy.",
"The urgent is rarely the important.",
"A short walk changes a long day.",
"Cold water on your wrists. Try it.",
"When stuck, change altitude — stand up, go outside.",
"Ten deep breaths. That is the entry fee.",
"Journal until the noise thins out.",
"The body keeps the score. Move it kindly.",
"Screens dim, mind clears.",
"Stretch what feels tight. Rest what feels tired.",
"Say the hard thing to a page first.",
"Boundaries are directions, not walls.",
"Say no, so your yes can mean something.",
"You have survived every hard day so far. That is a streak.",
"Ten years from now, this is a small chapter.",
"You are not late. You are on your own timeline.",
"Comparison is the thief of joy. Close the tab.",
"Your only competitor is who you were yesterday.",
"The mountain does not care how you climb it.",
"Everyone is figuring it out. Every one.",
"There is no finish line. There is only how you show up.",
"You are allowed a version of success that looks like peace.",
"Wanting a slower life is not laziness.",
"The best days often look ordinary.",
"You do not have to want what everyone else wants.",
"Ambition and rest can share a life.",
"Some seasons are for building, some for tending.",
"Not every year is meant to be your loudest.",
"The good life is smaller than the internet says.",
"Boring routines build interesting lives.",
"The average of your friends is a better predictor than the average on your feed.",
"You are the story you tell about yourself. Choose it kindly.",
"You will be different next year. Let it happen.",
"The person you are becoming will thank the person you are today.",
"You are the sum of the choices you defend when you are tired.",
"Small joys count. Track them.",
"You are richer in moments than in things.",
"Attention is the truest currency.",
"Where you look, you go.",
"A quiet life is not a wasted one.",
"You do not have to be the main character today.",
"Some days are just for maintenance. That is enough.",
"You are made of days like this one.",
"You have done hard things before. You will do them again.",
"You can be scared and still move.",
"Feelings are not orders.",
"Falling apart is sometimes the beginning of putting yourself together on purpose.",
"You are stronger than the story you are telling right now.",
"There is a version of you that has already made it. Walk toward them.",
"You do not need permission to try again.",
"Keep going. Quietly is fine.",
"Your effort is not invisible, even if no one is watching.",
"You are made of thousands of small comebacks.",
"You can do the next hour. Start there.",
"You are allowed to want more, and to be grateful now.",
"You are allowed to change everything.",
"Nothing is wasted. Even the detour taught you something.",
"You are more resilient than convenient.",
"The obstacle is often the path.",
"You will not always feel this way.",
"Bad days do not cancel good progress.",
"You can rebuild. You have before.",
"There is a way through. Keep listening.",
"You are allowed to hope again.",
"Try one more time, in a different way.",
"Kindness to yourself is a strategy, not a weakness.",
"You have carried harder days. You can carry this one.",
"You are not broken. You are becoming.",
"The dark does not last. Neither does the light. Both are fine.",
"You will surprise yourself.",
"You are held by more than you realize.",
"You can begin the day again at any hour.",
"You are not too late to become who you want to be.",
"Sleep is not the enemy of productivity. It is the source.",
"The day does not need one more thing. Close it.",
"Your bed is not a battlefield. Set it down.",
"Tomorrow starts tonight.",
"Dim the lights before you dim your mind.",
"A tired mind writes fiction. Sleep on it.",
"Let the day end without a verdict.",
"You did enough today.",
"Rest without earning it. Try it.",
"Put the phone in another room. See what happens.",
"The world will keep turning without your attention.",
"Notifications can wait. Your nervous system cannot.",
"Sleep is a form of loyalty to yourself.",
"Close the loops with a list, then close your eyes.",
"You are allowed to end the day undone.",
"The body needs boring evenings.",
"Nothing important gets solved after midnight.",
"Trust the morning with what is left.",
"Wind down like the sun does — gradually, without apology.",
"Even the moon rests half the month.",
"Rivers do not rush. They arrive.",
"Trees grow slow and stand long.",
"The seed does not doubt the season.",
"Storms are temporary tenants.",
"Even the earth needs winter.",
"Mountains are made of patience.",
"The tide always comes back.",
"Roots grow in the dark.",
"A candle does not lose light by lighting another.",
"The moon does not ask permission to be full.",
"Ferns unfurl slowly for a reason.",
"Every sunrise is a second chance rehearsal.",
"The ocean is calm at depth, no matter the surface.",
"Bamboo bends. That is its strength.",
"Rivers carve canyons one drop at a time.",
"The sky rearranges itself daily. So can you.",
"Even bare branches hold sky.",
"You are more forest than tree. Give yourself variety.",
"Snow melts. So do problems, given time.",
"The garden does not hurry, yet everything is done.",
"What you feed grows. What you starve dies.",
"Attention is love in action.",
"Pick one thing. Do it well.",
"Multitasking is thinking badly at several things at once.",
"Depth over breadth today.",
"Do the thing that scares you first.",
"Close the twenty tabs.",
"Choose your hard.",
"Say no to good so you can say yes to great.",
"Focus is a form of self-respect.",
"The next 25 minutes are yours. Guard them.",
"You can only do one thing. So do it.",
"Half your energy comes from where you point it.",
"Trade urgency for intention.",
"A quiet workspace, a quiet mind.",
"Distraction is a habit. So is presence.",
"Turn off the noise. The signal is quieter than you think.",
"You do not need a better plan. You need the next hour.",
"Deep work is a kindness to your future self.",
"Single-task and see what unfolds.",
"Feelings are weather, not climate.",
"You can hold sadness and gratitude in the same hand.",
"Cry when you need to. It clears the lens.",
"Anger is a messenger. Ask what it wants.",
"Fear is often love with the lights off.",
"Joy is a skill. Practice it in small ways.",
"You are not too much. You are just alive.",
"Loneliness is not a life sentence. It is a signal.",
"You are allowed to grieve things nobody sees.",
"Softness is the reward of feeling deeply and surviving it.",
"Your sensitivity is a compass. Follow it.",
"Not every wound needs to become a wall.",
"You can outgrow anger without abandoning yourself.",
"The heart is a muscle. It remembers.",
"Feel it. Move it through. Let it teach you.",
"Emotions are honest, even when they are wrong.",
"You are safe to feel this.",
"Big feelings do not need big responses.",
"Peace is not the absence of feeling. It is the room to feel.",
"Numb is not calm. Keep going.",
"You cannot pour from an empty cup, but you also do not have to fill everyone else's.",
"Choose people who make you feel more like yourself.",
"You are allowed to outgrow relationships.",
"Being liked and being loved are different currencies.",
"Not everyone deserves your explanation.",
"The right people leave you feeling lighter.",
"Space is a form of love.",
"You teach people how to treat you by what you accept.",
"You do not have to be the biggest one in the room.",
"Boundaries are not rejection. They are relief.",
"Speak with the softness you wish you had received.",
"Presence is the most expensive gift.",
"Listen like you have nowhere else to be.",
"Say the kind thing out loud.",
"Some people are chapters, not the whole book.",
"You can love someone and still leave.",
"You can miss someone and still choose peace.",
"The right people match your effort.",
"Ask for what you need. Softly. Twice, if needed.",
"You are allowed to be loved without earning it.",
"Your body is not a project. It is a home.",
"Move because it feels good, not because you have to earn food.",
"The body is honest. Listen to it.",
"Hydration is a mood.",
"Sunlight, then screen.",
"Walk daily. It untangles almost anything.",
"Your body carries you. Thank it.",
"Stretch what aches. Move what stagnates.",
"Sleep, water, sunlight, movement. In that order.",
"Every meal is a chance to be kind to yourself.",
"Rest is what makes strength possible.",
"The body forgives more than the mind remembers.",
"Warm shower, cold rinse. Try it.",
"Deep breathing is a free medicine.",
"Your posture is talking to your mood.",
"Nature is not optional. Get outside.",
"Screens off an hour before sleep.",
"Eat with your phone in the other room.",
"Your body is not the enemy. It is the ally.",
"Slow eating is a form of self-respect.",
"Not everything worth doing pays.",
"Not everything that pays is worth doing.",
"You are not your job title.",
"Rest is part of your job.",
"Ambition without rest is a fire that eats itself.",
"Your calendar is your values, printed.",
"Do less, better.",
"Say no to protect your yes.",
"Boring routines free your brain for interesting work.",
"Meetings are not work. Making things is work.",
"Notes are cheaper than memory.",
"Ship the small thing.",
"Version one exists. That is the point.",
"Perfection is procrastination with a nicer outfit.",
"Craftsmanship is patience with love.",
"Your work does not have to go viral to matter.",
"Slow money and steady growth beat fast money and burnout.",
"You are not behind. You are on your own timeline.",
"A quiet portfolio can still be powerful.",
"Take the walk before the meeting.",
"You do not have to know. You have to be curious.",
"Beginners have the best days.",
"Ask the obvious question.",
"Notes are how you remember what you were.",
"Learning is a loop, not a line.",
"You are always a beginner at the next thing.",
"Curiosity is a kind of courage.",
"Read a little every day.",
"The teacher appears when the student is ready.",
"Understanding is a form of respect.",
"You do not have to be gifted. You have to be interested.",
"Practice in public. Learn faster.",
"Take the class. Read the book. Ask the question.",
"You will forget most of it. Do it anyway.",
"Slow reading is a superpower.",
"Copy first, then invent.",
"Master the boring parts first.",
"Ideas are cheap. Attention is not.",
"Write to think, not to publish.",
"Teach it to remember it.",
"Kindness is a strategy that always pays.",
"Be the calm you needed as a kid.",
"Say the compliment out loud.",
"Small kindnesses compound.",
"You do not know what someone else is carrying.",
"Choose gentle. Always.",
"Assume good intent, verify with time.",
"Give without keeping score.",
"Notice, then thank.",
"Text them first.",
"Send the postcard.",
"Show up. Even briefly. Even quietly.",
"Presence is a gift with no wrapping.",
"You do not have to fix. Just listen.",
"Everyone is fighting a battle you know nothing about.",
"Extend the grace you wish someone gave you.",
"Say the eulogy while they can hear it.",
"Small talk can be a bridge, not a burden.",
"Warmth is a discipline.",
"The best gift is your undivided attention.",
"The days are long, the years are short.",
"Time spent on peace is never wasted.",
"There is enough time for what matters.",
"You do not have to hurry the rest of your life.",
"Do the thing you keep almost doing.",
"A year of small mornings is a life.",
"The past is a place, not a home.",
"The future is a hypothesis. The present is where you live.",
"Later is not a plan.",
"Choose ten years, not ten minutes.",
"Give it a decade, quietly.",
"You are exactly on time.",
"Slow years, honest days.",
"Some things can only be understood in slow motion.",
"You do not have to catch up. You are not behind.",
"Time is the price of everything real.",
"Guard your mornings.",
"The best time was ten years ago. The second best is now.",
"You are allowed to spend an hour on something small and beautiful.",
"Wasted time is only time spent against your values.",
"Notice one small thing today.",
"Thank the ordinary.",
"Gratitude is a lens, not a mood.",
"There is always something to notice.",
"Say thank you like you mean it.",
"The floor beneath you. The breath in you. The day around you.",
"Warm drink, quiet chair, a moment.",
"You woke up. That is a beginning.",
"The mundane is a kind of miracle.",
"Look for beauty like it is your job.",
"A grateful mind sleeps better.",
"Write down three good things.",
"The best luxuries are quiet.",
"There is a lot to love, if you slow down enough to see it.",
"Enough is a superpower.",
"Delight is available, even now.",
"Notice the light on the wall.",
"Beauty is on the way. Look up.",
"There is a life happening around you right now. Join it.",
"You are alive in one of the miracles.",
"You can change. You have before.",
"You are allowed to become someone new.",
"The old you got you here. The new you takes you there.",
"Growth requires unlearning.",
"You are more flexible than the story you are telling.",
"Nothing is fixed. Not you, not this.",
"Change begins as a whisper.",
"Small decisions, repeated, become a life.",
"You can renegotiate anything.",
"The next chapter begins the moment you decide it does.",
"You are allowed to stop, mid-sentence.",
"You do not owe your past self loyalty at the cost of your future.",
"You can choose again.",
"You are not the person you were in your worst hour.",
"You can be new by lunchtime.",
"You are one honest decision from a different life.",
"Change your inputs, change your outputs.",
"You do not need a fresh year to start fresh.",
"Wednesday is a great day to begin.",
"You can start anywhere. Start here.",
"Do it scared.",
"Courage is fear that showed up anyway.",
"You are braver than the story in your head.",
"The scariest step is usually the smallest.",
"On the other side of the fear is the life.",
"You can be nervous and prepared.",
"Send the message.",
"Apply anyway.",
"Ask for it.",
"Say the thing.",
"Bet on yourself, quietly.",
"You have permission you have been waiting for.",
"The worst outcome is usually survivable.",
"Fear shrinks when you name it.",
"You can rehearse the courage.",
"Doubt is a passenger, not a driver.",
"Move first. Feelings catch up.",
"You do not have to feel ready. Just begin.",
"Bravery is a boring, daily verb.",
"The comfort zone is a beautiful place, but nothing grows there.",
"You do not have to explain yourself to everyone.",
"Silence is an answer too.",
"Not every opinion deserves your reply.",
"Some things get better if you say them less.",
"Save your voice for what matters.",
"Silence around bad ideas kills them faster than argument.",
"You are allowed to opt out of the conversation.",
"Not everything needs a hot take.",
"Speak less. Choose more.",
"Some seasons are for listening.",
"Silence is a form of intimacy.",
"A quiet person is not a small person.",
"Your restraint is not your weakness.",
"The unsaid word is often the wisest one.",
"Not every notification is a summons.",
"You can leave the room.",
"You can decline the meeting.",
"You can close the app.",
"The world is loud. You do not have to match it.",
"Softly is still forward.",
"Look back kindly.",
"You did the best you could with what you had.",
"Old you was doing new things. Be kind.",
"Nothing was wasted.",
"Even the wrong turns took you somewhere.",
"You have already done impossible things.",
"You have already been the person you needed.",
"You are the answer to somebody's prayer.",
"You have already survived 100 percent of your worst days.",
"You are the sum of everything you have loved.",
"Your story is not over yet.",
"You are becoming a great ancestor.",
"You are the ceiling you did not have.",
"You are more than your résumé.",
"Your kindness will be remembered longer than your accolades.",
"Look for your own progress. It is quieter than you think.",
"You have been carried, even when you felt alone.",
"You are more loved than you know.",
"You have made someone's day, without knowing it.",
"You are needed. Even the quiet way you show up.",
"Take the long way home.",
"Pet the dog.",
"Order the dessert.",
"Sit in the sun.",
"Reread the good book.",
"Rewatch the comfort movie.",
"Nap without guilt.",
"Have the second coffee.",
"Text the friend.",
"Sing in the car.",
"Dance in the kitchen.",
"Buy the flowers.",
"Wear the nice sweater today.",
"Take the scenic route.",
"Read something that is not useful.",
"Cook a slow dinner.",
"Watch the sunset without a phone.",
"Light a candle before you start.",
"Make your bed. It sets the tone.",
"Take yourself out.",
"Write a letter you never send.",
"Send a letter you have been meaning to.",
"Draw something badly.",
"Play. Adults are allowed.",
"Follow a small curiosity to see where it leads.",
"Do one thing with your hands today.",
"Learn a stranger's name.",
"Compliment out loud.",
"Notice the sky.",
"Look up more.",
"Do work you would still want to do if no one noticed.",
"You do not have to have a purpose. You have to have a next step.",
"Purpose is built, not found.",
"The path finds you when you keep walking.",
"You do not need a mission statement. You need a Tuesday.",
"Meaning grows in the doing.",
"You will not find your purpose sitting still, forever.",
"Chase a curiosity. It will introduce you to a life.",
"Passion follows practice.",
"Your life is not late. It is unfinished.",
"You are allowed to have more than one thing.",
"Nothing has to be forever.",
"A season of experimenting is not a wasted year.",
"Meaning is quiet. Listen for it.",
"You do not have to know the ending.",
"Do things that make you lose track of time.",
"Follow the energy. It is the map.",
"Meaningful is often small.",
"You are allowed a life without labels.",
"You are allowed to define success on your own terms.",
"You are worth the time it takes to rest.",
"You will not always feel this heavy.",
"You are allowed to change your pace.",
"The pause is not a defeat.",
"Try again in the morning.",
"You can put it down.",
"You can pick it back up later.",
"You are not required to hustle for your worth.",
"You are allowed to want a simple life.",
"You are allowed to want a big life.",
"You get to decide.",
"You are trusted with your own choices.",
"You are not obligated to explain.",
"You can want less. It is still enough.",
"You can want more. That is human.",
"Comparison steals presence. Come back.",
"You are not behind on anyone else's timeline.",
"There is no age limit on becoming.",
"You are still early, in the best sense.",
"You are more capable when you are rested.",
"Take yourself less seriously. Take your peace more seriously.",
"You cannot heal in the environment that made you sick.",
"Choose environments that let you breathe.",
"Curate your inputs like you curate your friends.",
"You become what you consume.",
"Feed your mind slowly.",
"Boredom is a doorway. Walk through it.",
"You do not have to fill every silence.",
"You do not have to answer immediately.",
"You can sleep on it.",
"You can circle back tomorrow.",
"You are allowed a slow answer.",
"You are allowed a soft life.",
"You are allowed to be new at things.",
"You are allowed to be old at things.",
"You are allowed to stop performing.",
"You are allowed to be seen resting.",
"You are allowed to be seen struggling.",
"You are allowed to be seen thriving.",
"Softness will not make you invisible.",
"Quiet strength is still strength.",
"Do it with love or do not do it.",
"Slow down until the joy comes back.",
"Move at the speed of joy.",
"Choose the day you can sustain, not the day that looks impressive.",
"Sustainable is more powerful than spectacular.",
"Show up for the long game.",
"You have your whole life to be great. Just be present today.",
"Great days are stacked ordinary ones.",
"You are building a life, one hour at a time."
];
